---
# SPDX-FileCopyrightText: © 2020 kind-voltha contributors
# SPDX-License-Identifier: Apache-2.0

config:
  dryRun: false
  whitelistedNamespaces: voltha
  debug:
    enabled: true
    schedule_immediate_kill: true
args:
  logLevel: 5
